const img="https://res.cloudinary.com/read-cv/image/upload/c_limit,h_484,w_430/dpr_1.0/v1/1/users/e4F3qTUKtkbw8HP0qa80MMejX5R2/post-803df72d-c6a4-45f1-acc8-54ac1796a857.png?_a=DATAdtAAZAA0"

export const sources =[
  {username:"John Doe",
    title:"New York Creative Meet",
    url:"/explore/john-doe",
    content:" Sed do eiusmod tempor aliqua.",
    image:img},
  {username:"Jane Doe",
    title:"New York Creative Meet",
    url:"/explore/jane-doe",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:"https://res.cloudinary.com/read-cv/image/upload/c_limit,h_512,w_512/v1/1/profileItems/piOFyVriYxdFU9fwbkJa2OcHE0B3/newProfileItem/4965e22e-5a25-42af-9705-25045cc0ca5f.png?_a=DATAdtAAZAA0"},
  {username:"John Smith",
    title:"New York Creative Meet",
    url:"/explore/john-smith",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:"https://res.cloudinary.com/read-cv/image/upload/c_limit,h_512,w_512/v1/1/profileItems/e4F3qTUKtkbw8HP0qa80MMejX5R2/V26Zqhj3IS5thu166a05/60a702c7-0c25-42c1-8546-97b7836bf04c.png?_a=DATAdtAAZAA0"},
  {username:"Jane Smith",
    title:"New York Creative Meet",
    url:"/explore/jane-smith",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
  {username:"John Doe",
    title:"New York Creative Meet",
    url:"/explore/john-doe",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:"https://res.cloudinary.com/read-cv/image/upload/c_limit,h_512,w_512/v1/1/profileItems/fTE8oYeF5JXJR5lcYOZLyUUx2o32/TLxfO1dMQz7e89K9NXV1/f85bb809-3f3a-44cd-81b2-8f7fa9506c19.jpg?_a=DATAdtAAZAA0"},
  {username:"Jane Doe",
    title:"New York Creative Meet",
    url:"/explore/jane-doe",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
  {username:"John Smith",
    title:"New York Creative Meet",
    url:"/explore/john-smith",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
  {username:"Jane Smith",
    title:"New York Creative Meet",
    url:"/explore/jane-smith",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
  {username:"John Doe",
    title:"New York Creative Meet",
    url:"/explore/john-doe",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
  {username:"Jane Doe",
    title:"New York Creative Meet",
    url:"/explore/jane-doe",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
  {username:"John Smith",
    title:"New York Creative Meet",
    url:"/explore/john-smith",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
  {username:"Jane Smith",
    title:"New York Creative Meet",
    url:"/explore/jane-smith",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},

  {username:"John Doe",
    title:"New York Creative Meet",
    url:"/explore/john-doe",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
  {username:"Jane Doe",
    title:"New York Creative Meet",
    url:"/explore/jane-doe",
    content:"Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
  {username:"John Smith",
    title:"New York Creative Meet",
    url:"/explore/john-smith",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
  {username:"Jane Smith",
    title:"New York Creative Meet",
    url:"/explore/jane-smith",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
  {username:"John Doe",
    title:"New York Creative Meet",
    url:"/explore/john-doe",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
  {username:"Jane Doe",
    title:"New York Creative Meet",
    url:"/explore/jane-doe",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
  {username:"John Smith",
    title:"New York Creative Meet",
    url:"/explore/john-smith",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
  {username:"Jane Smith",
    title:"New York Creative Meet",
    url:"/explore/jane-smith",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
  {username:"John Doe",
    title:"New York Creative Meet",
    url:"/explore/john-doe",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
  {username:"Jane Doe",
    title:"New York Creative Meet",
    url:"/explore/jane-doe",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
  {username:"John Smith",
    title:"New York Creative Meet",
    url:"/explore/john-smith",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
  {username:"Jane Smith",
    title:"New York Creative Meet",
    url:"/explore/jane-smith",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:img},
    {username:"John Doe",
      title:"New York Creative Meet",
      url:"/explore/john-doe",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"Jane Doe",
      title:"New York Creative Meet",
      url:"/explore/jane-doe",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"John Smith",
      title:"New York Creative Meet",
      url:"/explore/john-smith",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"Jane Smith",
      title:"New York Creative Meet",
      url:"/explore/jane-smith",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing  tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"John Doe",
      title:"New York Creative Meet",
      url:"/explore/john-doe",
      content:"Lorem ipsum dolor sit amet,labore et dolore magna aliqua.",
      image:img},
    {username:"Jane Doe",
      title:"New York Creative Meet",
      url:"/explore/jane-doe",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"John Smith",
      title:"New York Creative Meet",
      url:"/explore/john-smith",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"Jane Smith",
      title:"New York Creative Meet",
      url:"/explore/jane-smith",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"John Doe",
      title:"New York Creative Meet",
      url:"/explore/john-doe",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"Jane Doe",
      title:"New York Creative Meet",
      url:"/explore/jane-doe",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"John Smith",
      title:"New York Creative Meet",
      url:"/explore/john-smith",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"Jane Smith",
      title:"New York Creative Meet",
      url:"/explore/jane-smith",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
  
    {username:"John Doe",
      title:"New York Creative Meet",
      url:"/explore/john-doe",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"Jane Doe",
      title:"New York Creative Meet",
      url:"/explore/jane-doe",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"John Smith",
      title:"New York Creative Meet",
      url:"/explore/john-smith",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"Jane Smith",
      title:"New York Creative Meet",
      url:"/explore/jane-smith",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"John Doe",
      title:"New York Creative Meet",
      url:"/explore/john-doe",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"Jane Doe",
      title:"New York Creative Meet",
      url:"/explore/jane-doe",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"John Smith",
      title:"New York Creative Meet",
      url:"/explore/john-smith",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"Jane Smith",
      title:"New York Creative Meet",
      url:"/explore/jane-smith",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"John Doe",
      title:"New York Creative Meet",
      url:"/explore/john-doe",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"Jane Doe",
      title:"New York Creative Meet",
      url:"/explore/jane-doe",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"John Smith",
      title:"New York Creative Meet",
      url:"/explore/john-smith",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},
    {username:"Jane Smith",
      title:"New York Creative Meet",
      url:"/explore/jane-smith",
      content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      image:img},












]

const user = {
  username: "John Doe",
  name: "John Doe",
  image: img,
  bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  workExperience: [
    {
      company: "Google",
      title: "Software Engineer",
      startDate: "2020-01-01",
      endDate: "2021-01-01",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    },
    {
      company: "Facebook",
      title: "Software Engineer",
      startDate: "2020-01-01",
      endDate: "2021-01-01",
    },
    {
      company: "Twitter",
      title: "Software Engineer",
      startDate: "2020-01-01",
      endDate: "2021-01-01",
    },

    {
      company: "Instagram",
      title: "Software Engineer",
      startDate: "2020-01-01",
      endDate: "2021-01-01",
    },
    
  ],
}
